"""add razorpay fields to orders

Revision ID: 259daeeda93b
Revises: 3259d1fbfc26
Create Date: 2025-12-31 21:59:08.370667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259daeeda93b'
down_revision = '3259d1fbfc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')

    # ### end Alembic commands ###
