"""rebuild migration history

Revision ID: 3259d1fbfc26
Revises: 24f9052d3f9a
Create Date: 2025-12-31 19:53:11.830286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3259d1fbfc26'
down_revision = '24f9052d3f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('shipping_address_line_1', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('shipping_address_line_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_pincode', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_pincode')
        batch_op.drop_column('shipping_state')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address_line_2')
        batch_op.drop_column('shipping_address_line_1')
        batch_op.drop_column('shipping_phone')
        batch_op.drop_column('shipping_name')

    op.drop_table('user_addresses')
    # ### end Alembic commands ###
