"""add user phone number

Revision ID: 52cbcab12b67
Revises: e256df771e74
Create Date: 2026-01-03 22:53:35.180110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52cbcab12b67'
down_revision = 'e256df771e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('discount_rules')
    # op.drop_table('order_discounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('whatsapp_opt_in')
        batch_op.drop_column('phone')

    # op.create_table('order_discounts',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('discount_rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('discount_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    # sa.Column('discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['discount_rule_id'], ['discount_rules.id'], name=op.f('order_discounts_discount_rule_id_fkey')),
    # sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_discounts_order_id_fkey')),
    # sa.PrimaryKeyConstraint('id', name=op.f('order_discounts_pkey'))
    # )
    # op.create_table('discount_rules',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    # sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('eligibility', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('stackable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('discount_rules_pkey'))
    # )
    # ### end Alembic commands ###
