"""add shipping fields to orders

Revision ID: bb831185110c
Revises: a6c0acc0bc84
Create Date: 2026-01-01 17:11:02.073469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb831185110c'
down_revision = 'a6c0acc0bc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shipping_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('awb_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('courier_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('courier_name')
        batch_op.drop_column('awb_code')
        batch_op.drop_column('shipping_order_id')
        batch_op.drop_column('shipping_provider')

    # ### end Alembic commands ###
