"""add aspect_ratio to product_variant_images

Revision ID: f37e4d9785a4
Revises: fba045f7cb7c
Create Date: 2026-03-28 23:11:11.045167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37e4d9785a4'
down_revision = 'fba045f7cb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspect_ratio', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant_images', schema=None) as batch_op:
        batch_op.drop_column('aspect_ratio')

    # ### end Alembic commands ###
