"""add bogo columns to cartitem

Revision ID: fba045f7cb7c
Revises: 6b919fc69390
Create Date: 2026-02-08 23:05:11.365674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba045f7cb7c'
down_revision = '6b919fc69390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_free_item', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parent_cart_item_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('parent_cart_item_id')
        batch_op.drop_column('is_free_item')

    # ### end Alembic commands ###
